apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    # This is a fake provider for testing purposes
    # In a real world scenario, you would use a different provider instead of storing the secret in plain text
    fake:
      data:
        - key: "api-key"
          value: "fake-secret-value"
          version: "v1"
