apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: external-secrets
  sources:
    - repoURL: https://github.com/pierreyves-lebrun/minikube-pulumi-gitops
      targetRevision: HEAD
      path: apps/external-secrets
    - repoURL: https://github.com/external-secrets/external-secrets.git
      targetRevision: helm-chart-0.17.0
      path: deploy/crds
    - repoURL: https://github.com/external-secrets/external-secrets.git
      targetRevision: helm-chart-0.17.0
      path: deploy/charts/external-secrets
      helm:
        releaseName: external-secrets
