apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dummy-helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: dummy-helm
  data:
  - secretKey: api-key
    remoteRef:
      key: api-key
      version: v1
